export type Inventory = Record<string, number>;

export type ApartmentType =
  | "Deluxe"
  | "Luxury"
  | "Superior"
  | "Executive"
  | "Penthouse 1"
  | "Penthouse 2"
  | "Penthouse 3";

const standardKeys: string[] = [
  "Wassergläser",
  "Weingläser",
  "Teller",
  "Suppenteller",
  "Kuchenteller",
  "Tassen",
  "Espressotassen",
  "Teelöffel",
  "Esslöffel",
  "Kuchengabeln",
  "Gabeln",
  "Messer",
  "Küchenmesser",
  "Pfanne",
  "Topf",
  "Schneidebrett",
  "Toaster",
  "Wasserkocher",
  "Mikrowelle",
  "Fernseher Fern.",
  "Klima Fern.",
  "Wlan-Zettel",
  "Seife",
  "Duschgel",
  "Shampoo",
  "Lotion",
  "Handtücher",
  "Duschtusch",
  "Badvorleger",
  "Handlotion",
  "Kleenex",
  "Küchenpapierrollen",
];

export const apartmentStandards: Record<ApartmentType, Inventory> = {
  Deluxe: {
    Wassergläser: 5,
    Weingläser: 3,
    Teelöffel: 5,
    Esslöffel: 5,
    Gabeln: 5,
    Kuchengabeln: 5,
    Buttermesser: 4,
    Küchenmesser: 2,
    Schneidebrett: 2,
    Espressotassen: 3,
    Kaffeetassen: 3,
    Kuchenteller: 4,
    Kaffeeunterteller: 3,
    Teller: 4,
    Suppenteller: 4,
    Pfanne: 1,
    Topf: 1,
    Wasserkocher: 1,
    Toaster: 1,
    Mikrowelle: 0,
    Handtücher: 2,
    Duschtusch: 2,
    Badvorleger: 1,
    Föhn: 1,
    "Duschgel/Seife": 2,
    Handlotion: 1,
    Kleenex: 1,
    "Klima Fern.": 1,
    "Fernseher Fern.": 1,
    "Wlan-Zettel": 1,
  },
  Luxury: {
    Wassergläser: 6,
    Weingläser: 4,
    Teelöffel: 6,
    Esslöffel: 6,
    Gabeln: 6,
    Kuchengabeln: 6,
    Buttermesser: 5,
    Küchenmesser: 2,
    Schneidebrett: 2,
    Espressotassen: 4,
    Kaffeetassen: 4,
    Kuchenteller: 5,
    Kaffeeunterteller: 4,
    Teller: 5,
    Suppenteller: 5,
    Pfanne: 2,
    Topf: 2,
    Wasserkocher: 1,
    Toaster: 1,
    Mikrowelle: 1,
    Handtücher: 2,
    Duschtusch: 2,
    Badvorleger: 1,
    Föhn: 1,
    "Duschgel/Seife": 2,
    Handlotion: 1,
    Kleenex: 1,
    "Klima Fern.": 1,
    "Fernseher Fern.": 1,
    "Wlan-Zettel": 1,
  },
  Superior: {
    Wassergläser: 4,
    Weingläser: 2,
    Teelöffel: 3,
    Esslöffel: 3,
    Gabeln: 3,
    Kuchengabeln: 3,
    Buttermesser: 3,
    Küchenmesser: 1,
    Schneidebrett: 1,
    Espressotassen: 2,
    Kaffeetassen: 2,
    Kuchenteller: 3,
    Kaffeeunterteller: 2,
    Teller: 3,
    Suppenteller: 3,
    Pfanne: 1,
    Topf: 1,
    Wasserkocher: 1,
    Toaster: 1,
    Mikrowelle: 0,
    Handtücher: 2,
    Duschtusch: 2,
    Badvorleger: 1,
    Föhn: 1,
    "Duschgel/Seife": 2,
    Handlotion: 1,
    Kleenex: 1,
    "Klima Fern.": 1,
    "Fernseher Fern.": 1,
    "Wlan-Zettel": 1,
  },
  Executive: {
    Wassergläser: 4,
    Weingläser: 2,
    Teelöffel: 3,
    Esslöffel: 3,
    Gabeln: 3,
    Kuchengabeln: 3,
    Buttermesser: 3,
    Küchenmesser: 1,
    Schneidebrett: 1,
    Espressotassen: 2,
    Kaffeetassen: 2,
    Kuchenteller: 3,
    Kaffeeunterteller: 2,
    Teller: 3,
    Suppenteller: 3,
    Pfanne: 1,
    Topf: 1,
    Wasserkocher: 1,
    Toaster: 1,
    Mikrowelle: 1,
    Handtücher: 2,
    Duschtusch: 2,
    Badvorleger: 1,
    Föhn: 1,
    "Duschgel/Seife": 2,
    Handlotion: 1,
    Kleenex: 1,
    "Klima Fern.": 1,
    "Fernseher Fern.": 1,
    "Wlan-Zettel": 1,
  },
  "Penthouse 1": {
    Wassergläser: 5,
    Weingläser: 3,
    Teelöffel: 5,
    Esslöffel: 5,
    Gabeln: 5,
    Kuchengabeln: 5,
    Buttermesser: 4,
    Küchenmesser: 2,
    Schneidebrett: 2,
    Espressotassen: 3,
    Kaffeetassen: 3,
    Kuchenteller: 4,
    Kaffeeunterteller: 3,
    Teller: 4,
    Suppenteller: 4,
    Pfanne: 1,
    Topf: 1,
    Wasserkocher: 1,
    Toaster: 1,
    Mikrowelle: 0,
    Handtücher: 2,
    Duschtusch: 2,
    Badvorleger: 1,
    Föhn: 1,
    "Duschgel/Seife": 2,
    Handlotion: 1,
    Kleenex: 1,
    "Klima Fern.": 1,
    "Fernseher Fern.": 1,
    "Wlan-Zettel": 1,
  },
  "Penthouse 2": {
    Wassergläser: 5,
    Weingläser: 3,
    Teelöffel: 5,
    Esslöffel: 5,
    Gabeln: 5,
    Kuchengabeln: 5,
    Buttermesser: 4,
    Küchenmesser: 2,
    Schneidebrett: 2,
    Espressotassen: 3,
    Kaffeetassen: 3,
    Kuchenteller: 4,
    Kaffeeunterteller: 3,
    Teller: 4,
    Suppenteller: 4,
    Pfanne: 1,
    Topf: 1,
    Wasserkocher: 1,
    Toaster: 1,
    Mikrowelle: 0,
    Handtücher: 2,
    Duschtusch: 2,
    Badvorleger: 1,
    Föhn: 1,
    "Duschgel/Seife": 2,
    Handlotion: 1,
    Kleenex: 1,
    "Klima Fern.": 1,
    "Fernseher Fern.": 1,
    "Wlan-Zettel": 1,
  },
  "Penthouse 3": {
    Wassergläser: 4,
    Weingläser: 2,
    Teelöffel: 3,
    Esslöffel: 3,
    Gabeln: 3,
    Kuchengabeln: 3,
    Buttermesser: 3,
    Küchenmesser: 1,
    Schneidebrett: 1,
    Espressotassen: 2,
    Kaffeetassen: 2,
    Kuchenteller: 3,
    Kaffeeunterteller: 2,
    Teller: 3,
    Suppenteller: 3,
    Pfanne: 1,
    Topf: 1,
    Wasserkocher: 1,
    Toaster: 1,
    Mikrowelle: 0,
    Handtücher: 2,
    Duschtusch: 2,
    Badvorleger: 1,
    Föhn: 1,
    "Duschgel/Seife": 2,
    Handlotion: 1,
    Kleenex: 1,
    "Klima Fern.": 1,
    "Fernseher Fern.": 1,
    "Wlan-Zettel": 1,
  },
};
